apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Check Balance Success Rate
  name: 8e2f0ba3-a984-49bf-b512-40d35e559429
  project: retail-banking-backend
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - countMetrics:
      good:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout",status="200"}[1m]))
      incremental: false
      total:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout"}[1m]))
    displayName: Check Balance Success Rate
    name: objective-1
    primary: false
    target: 0.998
    value: 0
  service: check-balance
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
