apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Checkout Error Rate
  labels:
    api:
    - 'true'
    industry:
    - payments
    onprem:
    - 'true'
  name: errors
  project: mobile-app
spec:
  alertPolicies:
  - fast-error-budget-drop
  - slow-error-budget-drop
  attachments:
  - displayName: SLO Definition
    url: https://gitlab.com/example/mobile-app/slo.yaml
  - displayName: Splunk
    url: https://splunk-test.nobl9.dev/en-US/account/login?return_to=%2Fen-US%2Fmanager%2Fsystem%2Flicensing
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: splunk
      project: integrations
  objectives:
  - displayName: Error Rate
    name: ok
    op: lt
    primary: false
    rawMetric:
      query:
        splunk:
          query: index=polakpotrafi-events source=udp:5072 sourcetype=syslog | bucket
            _time span=1m | stats count as n9value by _time | rename _time as n9time
            | fields n9time n9value
    target: 0.99
    value: 280
  service: checkout
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
