apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Ship Order Latency
  name: ship-order-latency
  project: opentelemetry-astronomy-shop
spec:
  alertPolicies:
  - fast-burn-alert-policy
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - displayName: ''
    name: objective-1
    op: lt
    primary: false
    rawMetric:
      query:
        gcm:
          projectId: n9-partner-sample-app
          promql: histogram_quantile(0.95,increase(rpc_client_duration_milliseconds_bucket{rpc_method="ShipOrder"}[1m]))
    target: 0.995
    value: 45
  service: shipping
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
