apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: User Journey
  labels:
    ad-group-name:
    - AD-N9-DigitalBankingPlatform-Owners
    app-id:
    - app-26f8ef6c
    business-criticality-tier:
    - tier1
    business-unit:
    - Demo Platforms
    cost-center:
    - CC-1000
    env-type:
    - prod
  name: 1f41cece-8df1-4063-9fea-ae51533fa8d5
  project: banking-app
spec:
  budgetingMethod: Occurrences
  description: ''
  objectives:
  - composite:
      aggregation: ErrorBudgetState
      components:
        objectives:
        - objective: check-balance-latency
          project: banking-app
          slo: check-balance-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: banking-app
          slo: 4fcb829e-b7dc-4652-884e-f4803c31e8e7
          weight: 1
          whenDelayed: Ignore
        - objective: login-latency
          project: banking-app
          slo: login-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: banking-app
          slo: dc90177f-25c5-47da-b90b-3e36576cbece
          weight: 1
          whenDelayed: Ignore
        - objective: pay-bill-latency
          project: banking-app
          slo: pay-bill-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: banking-app
          slo: b344c0b8-2362-4ff5-bef3-4aad015515e1
          weight: 1
          whenDelayed: Ignore
        - objective: statements-latency
          project: banking-app
          slo: statements-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: banking-app
          slo: 05d242d1-11a3-4314-a520-77ca76557bf5
          weight: 1
          whenDelayed: Ignore
      maxDelay: 1h
    displayName: Composite objective
    name: composite-objective
    target: 0.99
  service: pay-bill
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
