apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Payments Success Rate
  name: b344c0b8-2362-4ff5-bef3-4aad015515e1
  project: banking-app
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - countMetrics:
      good:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout",status="200"}[1m]))
      incremental: false
      total:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout"}[1m]))
    displayName: Payments Success Rate
    name: objective-1
    primary: false
    target: 0.999
    value: 0
  service: pay-bill
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
