apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Payments Latency
  name: pay-bill-latency
  project: banking-app
  labels:
    app-id:
    - app-26f8ef6c
    ad-group-name:
    - AD-N9-DigitalBankingPlatform-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
    business-criticality-tier:
    - tier1
spec:
  alertPolicies:
  - 10-error-budget-drop-over-10-min
  budgetingMethod: Occurrences
  description: Latency on a user clocking submit on paying a bill
  indicator:
    metricSource:
      kind: Direct
      name: appdynamics
      project: integrations
  objectives:
  - displayName: Latency
    name: pay-bill-latency
    op: lt
    primary: false
    rawMetric:
      query:
        appDynamics:
          applicationName: samplenodeapp
          metricPath: Overall Application Performance|Average Response Time (ms)
    target: 0.98
    value: 450
  service: pay-bill
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
