apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Pre-purchase user experience
  labels:
    composite-demo:
    - composite-demo
  name: pre-purchase-user-experience
  project: e-commerce
spec:
  alertPolicies:
  - fast-budget-drop
  - slow-budget-drop
  - slow-burn
  budgetingMethod: Occurrences
  description: Measures experience before user makes a purchase.
  objectives:
  - composite:
      aggregation: Reliability
      components:
        objectives:
        - objective: availability
          project: e-commerce
          slo: store-web-availability
          weight: 4
          whenDelayed: CountAsBad
        - objective: latency
          project: e-commerce
          slo: store-web-latency
          weight: 1
          whenDelayed: CountAsGood
      maxDelay: 45m
    displayName: Pre-purchase user experience
    name: pre-purchase-user-experience
    target: 0.9
  service: user-experience
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
