apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: User Experience of Purchase User Journey
  labels:
    composite-demo:
    - composite-demo
  name: purchase-user-journey-experience
  project: e-commerce
spec:
  alertPolicies:
  - fast-budget-drop
  - slow-budget-drop
  - slow-burn
  budgetingMethod: Occurrences
  description: Measures an overall experience of the entire user journey of a user
    purchasing an article.
  objectives:
  - composite:
      aggregation: Reliability
      components:
        objectives:
        - objective: pre-purchase-user-experience
          project: e-commerce
          slo: pre-purchase-user-experience
          weight: 5
          whenDelayed: CountAsBad
        - objective: post-purchase-user-experience
          project: e-commerce
          slo: post-purchase-user-experience
          weight: 2
          whenDelayed: CountAsBad
      maxDelay: 45m
    displayName: User Experience of Purchase User Journey
    name: purchase-user-journey-experience
    target: 0.9
  service: user-experience
  timeWindows:
  - calendar:
      startTime: '2020-04-01 00:00:00'
      timeZone: Europe/Warsaw
    count: 1
    isRolling: false
    period:
      begin: '2026-04-01T00:00:00+02:00'
      end: '2026-05-01T00:00:00+02:00'
    unit: Month
