apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Checkout
  labels:
    bu:
    - Global Investment Research
    cloud:
    - aws
    division:
    - Research & Perspectives
    engineering-service:
    - ES000006
  name: checkout
  project: mobile-app
spec:
  description: ''
