apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Login Success Rate
  labels:
    ad-group-name:
    - AD-N9-DigitalBankingPlatform-Owners
    app-id:
    - app-26f8ef6c
    business-criticality-tier:
    - tier1
    business-unit:
    - Demo Platforms
    cost-center:
    - CC-1000
    env-type:
    - prod
  name: dc90177f-25c5-47da-b90b-3e36576cbece
  project: banking-app
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - countMetrics:
      good:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout",status="200"}[1m]))
      incremental: false
      total:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout"}[1m]))
    displayName: Login Success Rate
    name: objective-1
    primary: false
    target: 0.998
    value: 0
  service: login
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
