apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Login Latency
  labels:
    ad-group-name:
    - AD-N9-DigitalBankingPlatform-Owners
    api:
    - 'true'
    app-id:
    - app-26f8ef6c
    business-criticality-tier:
    - tier1
    business-unit:
    - Demo Platforms
    cost-center:
    - CC-1000
    env-type:
    - prod
  name: login-latency
  project: banking-app
spec:
  alertPolicies:
  - 10-error-budget-drop-over-10-min
  budgetingMethod: Occurrences
  description: Latency on a user logging in
  indicator:
    metricSource:
      kind: Direct
      name: appdynamics
      project: integrations
  objectives:
  - displayName: Latency
    name: login-latency
    op: lt
    primary: false
    rawMetric:
      query:
        appDynamics:
          applicationName: samplenodeapp
          metricPath: Overall Application Performance|Average Response Time (ms)
    target: 0.99
    value: 475
  service: login
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
