apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Store Website Latency
  labels:
    composite-demo:
    - composite-demo
  name: store-web-latency
  project: e-commerce
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Agent
      name: prometheus
      project: e-commerce
  objectives:
  - displayName: Latency
    name: latency
    op: lt
    primary: true
    rawMetric:
      query:
        prometheus:
          promql: (time()*1+17)%(minute(vector(time()*1+17*60))+1)
    target: 0.9
    value: 40
  service: store-web
  timeWindows:
  - count: 14
    isRolling: true
    unit: Day
