apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Submit Booking
  labels:
    demo:
    - 'yes'
  name: submit-reservation
  project: bookings
spec:
  description: Service containing SLOs related to submitting reservations.
  responsibleUsers:
  - id: 00udz52enaMa5jKhf417
