apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Cart
  labels:
    demo:
    - 'yes'
  name: cart
  project: opentelemetry-astronomy-shop
spec:
  description: Service containing SLOs related to the cart services.
