apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Cancelation Success Rate
  name: cancelation-success-rate
  project: consumer-reservations
  labels:
    app-id:
    - app-80fde303
    ad-group-name:
    - AD-N9-ConsumerReservations-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
    business-criticality-tier:
    - tier1
spec:
  budgetingMethod: Occurrences
  description: Success Rate of cancelations
  indicator:
    metricSource:
      kind: Direct
      name: glitchy-zoomies
      project: integrations
  objectives:
  - displayName: ''
    name: objective-1
    op: gte
    rawMetric:
      query:
        gcm:
          projectId: glitchy-zoomies
          promql: (sum(increase(demo_requests_total{service="payments",path="/work",status=~"2.."}[1m])))
            / clamp_min(sum(increase(demo_requests_total{service="payments",path="/work"}[1m])),
            1)
    target: 0.99
    value: 0.995
  service: cancel-reservation
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
