apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Cancel Latency
  labels:
    application:
    - nobl9
    cloud:
    - aws
    app-id:
    - app-80fde303
    ad-group-name:
    - AD-N9-ConsumerReservations-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
    business-criticality-tier:
    - tier1
  name: latency
  project: consumer-reservations
spec:
  attachments:
  - displayName: runbook
    url: https://www.google.com
  - displayName: SLO definition doc
    url: https://www.google.com
  budgetingMethod: Occurrences
  description: Portal Latency
  indicator:
    metricSource:
      kind: Direct
      name: aws-direct-datasource
      project: integrations
  objectives:
  - displayName: Good
    name: objective-1
    op: lt
    primary: false
    rawMetric:
      query:
        cloudWatch:
          dimensions:
          - name: DBInstanceIdentifier
            value: main-rds-1-inst-a
          metricName: ReadLatency
          namespace: AWS/RDS
          region: eu-central-1
          stat: Average
    target: 0.97
    value: 0.008
  service: cancel-reservation
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
