apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Storefront
  labels:
    ad-group-name:
    - AD-N9-StorefrontPlatform-Owners
    app-id:
    - app-c36bf0f7
    business-criticality-tier:
    - tier1
    business-unit:
    - Demo Platforms
    cost-center:
    - CC-1000
    critical-app:
    - 'true'
    env-type:
    - prod
    owner:
    - dan-sepich
    service-tier:
    - tier1
  name: storefront
  project: storefront-platform-demo
spec:
  description: Front-door storefront experience for the demo application.
  reviewCycle:
    rrule: FREQ=MONTHLY;BYMONTHDAY=24
    startTime: '2026-05-24T12:00:00'
    timeZone: America/Chicago
