apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Search Latency
  labels:
    api:
    - 'true'
  name: search-latency
  project: consumer-reservations
spec:
  budgetingMethod: Occurrences
  description: Latency of search results
  indicator:
    metricSource:
      kind: Direct
      name: glitchy-zoomies
      project: integrations
  objectives:
  - displayName: Latency
    name: objective-2
    op: lte
    rawMetric:
      query:
        gcm:
          projectId: glitchy-zoomies
          promql: 1000 * histogram_quantile(0.90, sum by (le) (rate(demo_request_duration_seconds_bucket{service="recommendations",path="/work"}[1m])))
    target: 0.95
    value: 600
  service: search
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
