apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Add to Cart Success Rate
  name: add-to-cart-success-rate
  project: opentelemetry-astronomy-shop
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - countMetrics:
      good:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/cart",status="200"}[1m]))
      incremental: false
      total:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/cart"}[1m]))
    displayName: ''
    name: objective-1
    target: 0.999
    value: 0
  service: cart
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
