apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Submit Reservation Availability
  name: submit-reservation-availability
  project: consumer-reservations
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: dynatrace
      project: integrations
  objectives:
  - displayName: Submit API Avaialbility
    name: avaialbility
    op: gt
    primary: false
    rawMetric:
      query:
        dynatrace:
          metricSelector: builtin:synthetic.http.availability.location.total:filter(and(or(in("dt.entity.http_check",entitySelector("type(http_check),entityName.equals(~"www.wienershirtzel.com~")"))))):splitBy():sort(value(auto,descending)):limit(20)
    target: 0.99
    value: 99
  service: submit-reservation
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
