apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Customer Experience
  labels:
    demo:
    - 'yes'
  name: customer-experience
  project: opentelemetry-astronomy-shop
spec:
  description: Service containing composite SLOs related to the customer experience.
