apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Login Availability
  labels:
    ad-group-name:
    - AD-N9-StorefrontPlatform-Owners
    app-id:
    - app-c36bf0f7
    business-unit:
    - Demo Platforms
    cost-center:
    - CC-1000
    critical-app:
    - 'true'
    env-type:
    - prod
    owner:
    - demo-platform
    service-tier:
    - tier1
  name: login-availability
  project: storefront-platform-demo
spec:
  alertPolicies:
  - login-availability-fast-burn
  budgetingMethod: Occurrences
  description: Availability SLO for the customer login flow.
  indicator:
    metricSource:
      kind: Direct
      name: glitchy-zoomies
      project: integrations
  objectives:
  - countMetrics:
      good:
        gcm:
          projectId: glitchy-zoomies
          promql: sum(increase(demo_requests_total{service="login",path="/work",status=~"2.."}[1m]))
      incremental: false
      total:
        gcm:
          projectId: glitchy-zoomies
          promql: sum(increase(demo_requests_total{service="login",path="/work"}[1m]))
    displayName: Successful login checks
    name: availability
    target: 0.995
    value: 1
  service: customer-login
  timeWindows:
  - count: 7
    isRolling: true
    unit: Day
