apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: Inventory Availability Fast Burn
  labels:
    app-id:
    - app-c36bf0f7
    critical-app:
    - 'true'
    owner:
    - demo-platform
    service-tier:
    - tier2
    ad-group-name:
    - AD-N9-StorefrontPlatform-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
  name: inventory-availability-fast-burn
  project: storefront-platform-demo
spec:
  alertMethods: []
  conditions:
  - alertingWindow: 5m
    measurement: averageBurnRate
    op: gte
    value: 20
  coolDown: 5m
  description: Fast burn alert policy for Inventory availability.
  severity: High
