apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: 10% Error Budget Drop Over 10 Min
  name: 10-error-budget-drop-over-10-min
  project: consumer-reservations
spec:
  alertMethods: []
  conditions:
  - alertingWindow: 15m
    measurement: budgetDrop
    op: gte
    value: 0.1
  coolDown: 5m
  description: The budget dropped by 10% over the last 15 minutes and is not recovering.
  severity: High
