apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: 20% Remaining
  name: 20-remaining
  project: consumer-reservations
spec:
  alertMethods:
  - apiVersion: n9/v1alpha
    kind: AlertMethod
    metadata:
      displayName: Slack App Webhook Test
      name: slack-app-webhook-test
      project: default
    spec:
      description: Test config for slack app
      webhook:
        headers:
        - isSecret: true
          name: X-Webhook-Secret
          value: '[hidden]'
        templateFields:
        - alert_policy_name
        - alert_policy_description
        - alert_policy_conditions_text
        - project_name
        - service_name
        - slo_name
        - organization
        - objective_name
        - severity
        - timestamp
        - slo_details_link
        - iso_timestamp
        - slo_labels_text
        - service_labels_text
        - alert_policy_labels_text
        - alert_id
        - no_data_alert_after
        - anomaly_type
        - alert_policy_conditions[]
        url: '[hidden]'
  - apiVersion: n9/v1alpha
    kind: AlertMethod
    metadata:
      name: email
      project: e-commerce
    spec:
      description: ''
      email:
        to:
        - jakub.gruszecki+email-e-commerce-nobl9-dogfood-dev-demo-1@nobl9.com
  conditions:
  - lastsFor: 0m
    measurement: burnedBudget
    op: gte
    value: 0.8
  coolDown: 5m
  description: The error budget is nearly exhausted (20%).
  severity: High
