apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Error Rate
  name: availability
  project: demo
spec:
  attachments:
  - displayName: SLI Analysis
    url: https://app.nobl9.com/sli-analyzer/analysis/2024-06-06-09-02-cjkr/integrations?org=dansepich-2KadyONlKmHJ
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: dynatrace
      project: integrations
  objectives:
  - displayName: Avaialbility
    name: avaialbility
    op: gt
    primary: false
    rawMetric:
      query:
        dynatrace:
          metricSelector: builtin:synthetic.http.availability.location.total:filter(and(or(in("dt.entity.http_check",entitySelector("type(http_check),entityName.equals(~"www.wienershirtzel.com~")"))))):splitBy():sort(value(auto,descending)):limit(20)
    target: 0.99
    value: 99
  service: landing-page
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
