apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Customer Experience
  name: e072fba8-5804-400e-a2a4-909917c2266a
  project: demo
spec:
  alertPolicies:
  - 10x-burn-1-hour
  budgetingMethod: Occurrences
  description: ''
  objectives:
  - composite:
      aggregation: Reliability
      components:
        objectives:
        - objective: latency
          project: demo
          slo: latency-add-to-cart
          weight: 1
          whenDelayed: Ignore
        - objective: latency
          project: demo
          slo: latency
          weight: 1
          whenDelayed: Ignore
        - objective: avaialbility
          project: demo
          slo: availability
          weight: 1
          whenDelayed: Ignore
      maxDelay: 1h
    displayName: Composite objective
    name: composite-objective
    primary: false
    target: 0.99
  service: landing-page
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
