apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: User Experience
  labels:
    bu:
    - Global Investment Research
    division:
    - Research & Perspectives
    engineering-service:
    - ES000008
    onprem:
    - 'true'
    team:
    - red
    - blue
  name: user-experience
  project: mobile-app
spec:
  description: ''
