apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: Fast Burn
  name: fast-burn
  project: bookings
spec:
  alertMethods: []
  conditions:
  - alertingWindow: 5m
    measurement: averageBurnRate
    op: gte
    value: 20
  coolDown: 5m
  description: "There\u2019s been a significant spike in burn rate over a brief period."
  severity: High
