apiVersion: n9/v1alpha
kind: Project
metadata:
  displayName: Storefront Platform
  labels:
    app-id:
    - app-c36bf0f7
    critical-app:
    - 'true'
    owner:
    - demo-platform
    service-tier:
    - tier1
    ad-group-name:
    - AD-N9-StorefrontPlatform-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
  name: storefront-platform-demo
spec:
  description: Nobl9 project for the storefront platform reliability demo.
