apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: View Statements Success Rate
  name: 05d242d1-11a3-4314-a520-77ca76557bf5
  project: banking-app
  labels:
    app-id:
    - app-26f8ef6c
    ad-group-name:
    - AD-N9-DigitalBankingPlatform-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - countMetrics:
      good:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout",status="200"}[1m]))
      incremental: false
      total:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout"}[1m]))
    displayName: Statements Success Rate
    name: objective-1
    primary: false
    target: 0.999
    value: 0
  service: statements
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
