apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Recommendations Engine
  labels:
    app-id:
    - app-c36bf0f7
    critical-app:
    - 'true'
    owner:
    - dan-sepich
    service-tier:
    - tier2
    ad-group-name:
    - AD-N9-StorefrontPlatform-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
  name: recommendations-engine
  project: storefront-platform-demo
spec:
  description: Personalization dependency used to demonstrate downstream suggestion
    quality and latency changes.
  reviewCycle:
    rrule: FREQ=MONTHLY;BYMONTHDAY=24
    startTime: '2026-05-24T12:00:00'
    timeZone: America/Chicago
