apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Payments Success Rate
  name: 4e1bff61-9e0e-4d2a-9d14-059afee99fa1
  project: retail-banking-backend
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - countMetrics:
      good:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout",status="200"}[1m]))
      incremental: false
      total:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/checkout"}[1m]))
    displayName: Payments Success Rate
    name: objective-1
    primary: false
    target: 0.999
    value: 0
  service: payments
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
