apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: All Stores
  name: 52355d37-54b6-4d6a-b5e3-5004917bcc72
  project: point-of-sale
spec:
  alertPolicies:
  - 20-remainig
  budgetingMethod: Occurrences
  description: ''
  objectives:
  - composite:
      aggregation: Reliability
      components:
        objectives:
        - objective: availability
          project: point-of-sale
          slo: store-1-pos-availability
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: point-of-sale
          slo: store-1-pos-latency
          weight: 1
          whenDelayed: Ignore
        - objective: v
          project: point-of-sale
          slo: store-2-pos-availability
          weight: 1
          whenDelayed: Ignore
        - objective: availability
          project: point-of-sale
          slo: store-3-pos-availability
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: point-of-sale
          slo: store-3-pos-latency
          weight: 1
          whenDelayed: Ignore
        - objective: availability
          project: point-of-sale
          slo: store-4-pos-availability
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: point-of-sale
          slo: store-4-pos-latency
          weight: 1
          whenDelayed: Ignore
        - objective: availability
          project: point-of-sale
          slo: store-5-pos-availability
          weight: 1
          whenDelayed: Ignore
      maxDelay: 15m
    displayName: Composite objective
    name: composite-objective
    primary: false
    target: 0.98
  service: store-composite
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
