apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: User Experience
  labels:
    demo:
    - 'yes'
    app-id:
    - app-ddb899d8
    ad-group-name:
    - AD-N9-CallCenter-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
    business-criticality-tier:
    - tier1
  name: call-center-performance
  project: call-center
spec:
  description: Service containing SLOs related to Call Center KPIs.
  responsibleUsers:
  - id: 00udz52enaMa5jKhf417
