apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Invoicing System
  labels:
    composite-demo:
    - composite-demo
  name: invoices
  project: e-commerce
spec:
  description: Service responsible for generating invoices.
