apiVersion: n9/v1alpha
kind: Project
metadata:
  displayName: OpenTelemetry Astronomy Shop
  labels:
    demo:
    - 'yes'
  name: opentelemetry-astronomy-shop
spec:
  description: Project for OpenTelemetry Astronomy Shop demo SLOs
