apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  labels:
    composite-demo:
    - composite-demo
  name: slow-budget-drop
  project: e-commerce
spec:
  alertMethods:
  - apiVersion: n9/v1alpha
    kind: AlertMethod
    metadata:
      name: email
      project: e-commerce
    spec:
      description: ''
      email:
        to:
        - jakub.gruszecki+email-e-commerce-nobl9-dogfood-dev-demo-1@nobl9.com
  conditions:
  - alertingWindow: 1h
    measurement: budgetDrop
    op: gte
    value: 0.05
  coolDown: 5m
  description: The budget dropped by 5% over the last 1 hour and is not recovering.
  severity: Low
