apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  labels:
    composite-demo:
    - composite-demo
  name: slow-burn
  project: e-commerce
spec:
  alertMethods:
  - apiVersion: n9/v1alpha
    kind: AlertMethod
    metadata:
      name: email
      project: e-commerce
    spec:
      description: ''
      email:
        to:
        - jakub.gruszecki+email-e-commerce-nobl9-dogfood-dev-demo-1@nobl9.com
  conditions:
  - alertingWindow: 48h
    measurement: averageBurnRate
    op: gte
    value: 1
  - alertingWindow: 15m
    measurement: averageBurnRate
    op: gte
    value: 2
  coolDown: 5m
  description: The budget is slowly exhausting and not recovering.
  severity: Low
