apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Store 1
  labels:
    demo:
    - 'yes'
  name: store-1
  project: point-of-sale
spec:
  description: Service containing SLOs related to POS.
  responsibleUsers:
  - id: 00udz52enaMa5jKhf417
