apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: EasyTravel Server CPU utilization
  labels:
    source:
    - dynatrace
  name: easytravel-server-cpu-utilization
  project: demo
spec:
  budgetingMethod: Occurrences
  description: Keep CPU utilization below 70%
  indicator:
    metricSource:
      kind: Direct
      name: dynatrace
      project: integrations
  objectives:
  - displayName: CPU Utilization
    name: cpu-utilization
    op: lt
    rawMetric:
      query:
        dynatrace:
          metricSelector: builtin:host.cpu.usage:filter(and(or(in("dt.entity.host",entitySelector("type(host),entityName.equals(~"ip-172-31-11-2.eu-west-1.compute.internal~")"))))):splitBy():sort(value(auto,descending)):limit(20)
    target: 0.98
    value: 8
  service: easy-travel-application
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
