apiVersion: n9/v1alpha
kind: Project
metadata:
  displayName: Digital Banking Platform
  labels:
    demo:
    - 'yes'
    app-id:
    - app-26f8ef6c
    ad-group-name:
    - AD-N9-DigitalBankingPlatform-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
  name: banking-app
spec:
  description: Project for online banking SLOs
