apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Inventory Catalog
  labels:
    app-id:
    - storefront-platform-app
    critical-app:
    - 'true'
    owner:
    - dan-sepich
    service-tier:
    - tier2
  name: inventory-catalog
  project: storefront-platform-demo
spec:
  description: Critical dependency used to demonstrate latency degradation.
  reviewCycle:
    rrule: FREQ=MONTHLY;BYMONTHDAY=24
    startTime: 2026-05-24 12:00:00
    timeZone: America/Chicago
