apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: Fast Burn Alert Policy
  name: fast-burn-alert-policy
  project: opentelemetry-astronomy-shop
spec:
  alertMethods:
  - apiVersion: n9/v1alpha
    kind: AlertMethod
    metadata:
      displayName: Status Page Integration
      name: status-page-integration
      project: opentelemetry-astronomy-shop
    spec:
      description: ''
      webhook:
        headers:
        - isSecret: false
          name: Organization
          value: dansepich-2KadyONlKmHJ
        - isSecret: true
          name: Authorization
          value: '[hidden]'
        templateFields:
        - alert_policy_name
        - alert_policy_description
        - alert_policy_conditions_text
        - project_name
        - service_name
        - slo_name
        - organization
        - objective_name
        - severity
        - timestamp
        - slo_details_link
        - iso_timestamp
        - slo_labels_text
        - service_labels_text
        - alert_policy_labels_text
        - alert_id
        - no_data_alert_after
        - anomaly_type
        - alert_policy_conditions[]
        url: '[hidden]'
  conditions:
  - alertingWindow: 5m
    measurement: averageBurnRate
    op: gte
    value: 20
  coolDown: 5m
  description: "There\u2019s been a significant spike in burn rate over a brief period."
  severity: High
