apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Emailing System Availability
  labels:
    composite-demo:
    - composite-demo
  name: emailing-availability
  project: e-commerce
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Agent
      name: prometheus
      project: e-commerce
  objectives:
  - displayName: Availability
    name: availability
    op: lt
    primary: true
    rawMetric:
      query:
        prometheus:
          promql: (time()*1+5)%(minute(vector(time()*1+5*60))+1)
    target: 0.95
    value: 50
  service: emailing
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
