apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: User Experience
  name: user-experience
  project: mobile-app
spec:
  alertPolicies:
  - fast-error-budget-drop
  budgetingMethod: Occurrences
  description: Mobile application user experience
  objectives:
  - composite:
      aggregation: Reliability
      components:
        objectives:
        - objective: ok
          project: mobile-app
          slo: errors
          weight: 2
          whenDelayed: Ignore
        - objective: objective-1
          project: mobile-app
          slo: availability
          weight: 3
          whenDelayed: Ignore
      maxDelay: 5m
    displayName: User Experience
    name: user-experience
    target: 0.95
  service: user-experience
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
