apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: zzz
  name: zzz
  project: mobile-app
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Agent
      name: prometheus
      project: e-commerce
  objectives:
  - displayName: dndndgdng
    name: dndndgdng
    op: lt
    rawMetric:
      query:
        prometheus:
          promql: prometheus_build_info
    target: 0.12
    value: 45
  service: user-experience
  timeWindows:
  - count: 1
    isRolling: true
    unit: Hour
