apiVersion: n9/v1alpha
kind: Project
metadata:
  displayName: Consumer Queue
  labels:
    demo:
    - 'yes'
  name: consumer-queue
spec:
  description: Project for SLOs that are asyncronous in nature/queue based.
