apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: Fast Error Budget Drop
  labels:
    application:
    - nobl9
  name: fast-error-budget-drop
  project: mobile-app
spec:
  alertMethods:
  - apiVersion: n9/v1alpha
    kind: AlertMethod
    metadata:
      displayName: Custom Webhook
      name: custom-webhook
      project: demo
    spec:
      description: ''
      webhook:
        templateFields:
        - alert_policy_name
        - alert_policy_description
        - alert_policy_conditions_text
        - project_name
        - service_name
        - slo_name
        - organization
        - objective_name
        - severity
        - timestamp
        - slo_details_link
        - iso_timestamp
        - slo_labels_text
        - service_labels_text
        - alert_policy_labels_text
        - alert_policy_conditions[]
        url: '[hidden]'
  conditions:
  - alertingWindow: 15m
    measurement: budgetDrop
    op: gte
    value: 0.15
  coolDown: 5m
  description: The budget dropped by 10% over the last 15 minutes and is not recovering.
  severity: High
