apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: Slow burn
  name: slow-burn
  project: mobile-app
spec:
  alertMethods: []
  conditions:
  - lastsFor: 1h
    measurement: averageBurnRate
    op: gte
    value: 20
  coolDown: 5m
  description: "There\u2019s been a significant spike in burn rate over a brief period."
  severity: High
