apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Search Reservations
  labels:
    demo:
    - 'yes'
  name: search
  project: consumer-reservations
spec:
  description: Service containing SLOs related to searching for reservations.
