apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Customer Experience Composite
  name: customer-experience-composite
  project: opentelemetry-astronomy-shop
spec:
  budgetingMethod: Occurrences
  description: ''
  objectives:
  - composite:
      aggregation: Reliability
      components:
        objectives:
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: add-to-cart-success-rate
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: empty-cart-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: get-cart-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: checkout-success-rate
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: get-quote-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: make-payment-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: get-product-latency
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: get-product-success-rate
          weight: 1
          whenDelayed: Ignore
        - objective: objective-1
          project: opentelemetry-astronomy-shop
          slo: ship-order-latency
          weight: 1
          whenDelayed: Ignore
      maxDelay: 1h
    displayName: Composite objective
    name: composite-objective
    primary: false
    target: 0.995
  service: customer-experience
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
