apiVersion: n9/v1alpha
kind: Project
metadata:
  displayName: Consumer Reservations
  labels:
    demo:
    - 'yes'
    app-id:
    - app-80fde303
    ad-group-name:
    - AD-N9-ConsumerReservations-Owners
    cost-center:
    - CC-1000
    business-unit:
    - Demo Platforms
    env-type:
    - prod
    business-criticality-tier:
    - tier1
  name: consumer-reservations
spec:
  description: Project for SLOs that represent examples of reserverations being made.
