apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Frontend Avaialbility
  name: frontend-avaialbility
  project: opentelemetry-astronomy-shop
spec:
  alertPolicies:
  - fast-burn-alert-policy
  attachments:
  - displayName: SLI Analysis
    url: https://app.nobl9.com/sli-analyzer/analysis/2025-05-02-14-05-qwpe/gcm?org=gcp-training-mkGe06qumjIX
  - displayName: Synthetic
    url: https://console.cloud.google.com/monitoring/synthetic-monitoring/frontend-availability-REl1x-78O9s;duration=PT15M?cloudshell=true&hl=en&invt=AbwVnw&project=n9-partner-sample-app
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - displayName: Frontend Avialability
    name: frontend-avialability
    op: gte
    primary: false
    rawMetric:
      query:
        gcm:
          projectId: n9-partner-sample-app
          promql: avg(avg_over_time(monitoring_googleapis_com:uptime_check_check_passed{monitored_resource="cloud_run_revision",check_id="frontend-availability-REl1x-78O9s"}[1m]))
    target: 0.99
    value: 1
  service: product-catalog
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
