apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Get Product Success Rate
  name: get-product-success-rate
  project: opentelemetry-astronomy-shop
spec:
  budgetingMethod: Occurrences
  description: ''
  indicator:
    metricSource:
      kind: Direct
      name: n9-partner-sample-app
      project: integrations
  objectives:
  - countMetrics:
      good:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/products",status="200"}[1m]))
      incremental: false
      total:
        gcm:
          projectId: n9-partner-sample-app
          promql: sum(rate(app_frontend_requests_total{target="/api/products"}[1m]))
    displayName: ''
    name: objective-1
    primary: false
    target: 0.9975
    value: 0
  service: product-catalog
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
