apiVersion: n9/v1alpha
kind: SLO
metadata:
  displayName: Login Latency
  labels:
    api:
    - 'true'
  name: 02803482-605f-41a7-9f95-5914910bb520
  project: retail-banking-backend
spec:
  budgetingMethod: Occurrences
  description: Latency on a user logging in
  indicator:
    metricSource:
      kind: Direct
      name: appdynamics
      project: integrations
  objectives:
  - displayName: Latency
    name: login-latency
    op: lt
    primary: false
    rawMetric:
      query:
        appDynamics:
          applicationName: samplenodeapp
          metricPath: Overall Application Performance|Average Response Time (ms)
    target: 0.99
    value: 475
  service: login
  timeWindows:
  - count: 28
    isRolling: true
    unit: Day
