apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Payments
  labels:
    ad-group-name:
    - AD-N9-DigitalBankingPlatform-Owners
    app-id:
    - app-26f8ef6c
    business-criticality-tier:
    - tier1
    business-unit:
    - Demo Platforms
    cost-center:
    - CC-1000
    demo:
    - 'yes'
    env-type:
    - prod
  name: pay-bill
  project: banking-app
spec:
  description: Service containing SLOs related to pay bill services.
