apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: 10x burn 1 hour
  name: 10x-burn-1-hour
  project: demo
spec:
  alertMethods: []
  conditions:
  - lastsFor: 1h
    measurement: averageBurnRate
    op: gte
    value: 10
  coolDown: 5m
  description: The budget is slowly exhausting and not recovering.
  severity: Low
