apiVersion: n9/v1alpha
kind: AlertPolicy
metadata:
  displayName: Slow Burn
  name: slow-burn
  project: demo
spec:
  alertMethods: []
  conditions:
  - alertingWindow: 12h
    measurement: averageBurnRate
    op: gte
    value: 1
  - alertingWindow: 15m
    measurement: averageBurnRate
    op: gte
    value: 2
  coolDown: 5m
  description: The budget is slowly exhausting and not recovering.
  severity: Low
