apiVersion: n9/v1alpha
kind: Service
metadata:
  displayName: Search Bookings
  labels:
    demo:
    - 'yes'
  name: search
  project: bookings
spec:
  description: Service containing SLOs related to searching for reservations.
  responsibleUsers:
  - id: 00udz52enaMa5jKhf417
